---
- name: Install a full arch linux desktop
  hosts: fisicos
  tasks:
    - name: Apaga todos los contenedores
      command: "lxc-stop -n {{ item }}"
      with_items:
        - nagiosxi
        - servicios1
        - servicios2
        - reparar-bd
        - update
      become: yes
      ignore_errors: true
    - name: Destruye todos los contenedores
      command: "lxc-destroy -n {{ item }}"
      with_items:
        - nagiosxi
        - servicios1
        - servicios2
        - reparar-bd
        - update
      become: yes
      ignore_errors: true
    - name: Crea contenedor de nagiosxi
      lxc_container:
        name: nagiosxi
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 120
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac01 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes
    - name: Crea contenedor de servicios1
      lxc_container:
        name: servicios1
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 1
          - lxc.network.hwaddr = {{ mac02 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes    
    - name: Crea contenedor de servicios2
      lxc_container:
        name: servicios2
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 2
          - lxc.network.hwaddr = {{ mac03 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes
    - name: Crea contenedor de reparar-bd
      lxc_container:
        name: reparar-bd
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 2
          - lxc.network.hwaddr = {{ mac04 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes
    - name: Crea contenedor de update
      lxc_container:
        name: update
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 2
          - lxc.network.hwaddr = {{ mac05 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes
    - name: Crea configuración base para todos los contenedores
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'nagiosxi', 'servicios1', 'servicios2', 'reparar-bd', 'update']
        - [ 'yum update -y', 'yum install openssh-server sudo which psmisc -y', 'systemctl enable sshd', 'systemctl start sshd', 'useradd -s /bin/bash -G wheel -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore']
      become: yes
