---
- name: Instala la máquina virtual de FreePBX
  hosts: fisicos
  strategy: free
  tasks:
    - name: Instala paquetes requeridos por la receta
      apt:
        name: pbzip2
        state: present
      become: yes
    - name: Plantilla de jinja para XML de VM de FreePBX
      template:
        src: files/FreePBX.xml.j2
        dest: /tmp/FreePBX.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de FreePBX
      command: virsh define /tmp/FreePBX.xml
      become: yes
    - name: Mueve imagen de kali a directorio de imagenes
      get_url:
        url: http://{{ filesrv }}/vms/FreePBX.qcow2.bz2
        dest: /var/lib/libvirt/images/FreePBX.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
      become: yes
    - name: Descomprime imagen de FreePBX usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/FreePBX.qcow2.bz2
      become: yes
