---
- name: Actualiza los equipos fisicos a utilizar en las aulas
  hosts: contenedores
  strategy: free
  tasks:
    - name: Actualiza cache
      apt:
        update_cache: yes
      become: yes
    - name: Actualiza paquetes
      apt:
        upgrade: dist
      become: yes
      ignore_errors: true
    - name: autoremueve
      apt:
        autoremove: yes
      become: yes
