---
- name: Ajusta lo necesario para el correcto funcionamiento del SIGUCA 
  hosts: contenedores
  strategy: free
  tasks:
    - name: Cambia linea (62) en el modulo de multipart
      lineinfile:
        regexp: this.boundary.write\(\'\\r\\n--\'\, 'ascii', 0\)\;
        dest: "/usr/local/bin/siguca/node_modules/formidable/lib/multipart_parser.js"
        line: "  this.boundary.write('\\\\r\\\\n--', 0, 'ascii');"
        state: present
        backrefs: yes
      become: true
    - name: Cambia linea (63) en el modulo de multipart
      lineinfile:
        regexp: this.boundary.write\(str\, 'ascii'\, 4\)\;
        dest: "/usr/local/bin/siguca/node_modules/formidable/lib/multipart_parser.js"
        line: "  this.boundary.write(str, 4, 'ascii');"
        state: present
        backrefs: yes
      become: true
    - name: Cambia el IP localhost por el Servidor SIGUCA
      lineinfile:
        regexp: ^var socket \= io.connect\(\'http\:\/\/localhost\:3000\'\)\;
        dest: "/usr/local/bin/siguca/public/js/app/sigucaHomeEmpl.js"
        line: "var socket = io.connect('http://{{ ansible_facts['default_ipv4']['address'] }}:3000')"
        state: present
        backrefs: yes
      become: true
    - name: Cambia el IP localhost por el Servidor SIGUCA (2)
      lineinfile:
        regexp: ^var socket \= io.connect\(\'http\:\/\/localhost\:3000\'\)\;
        dest: "/usr/local/bin/siguca/public/js/app/sigucaHome.js"
        line: "var socket = io.connect('http://{{ ansible_facts.default_ipv4.address | ipaddr }}:3000)"
        state: present
        backrefs: yes
      become: true      
      tags: socket
    - name: Crear directorio de imagenes
      file: 
        path: /usr/local/bin/siguca/imagenes
        state: directory
        owner: root
        group: root
        mode: 0775
      become: true
      tags: directory
    - name: Iniciar SIGUCA
      systemd:
        name: siguca.service
        state: started
      become: true
      tags: start
