---
- name: Crea contenedores necesarios para el curso
  hosts: fisicos
  tasks:
    - name: Crea contenedor web-base
      lxc_container:
        name: web-base
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac01 }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor nagiosxi
      lxc_container:
        name: nagiosxi
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac02 }}
        template: download
        state: started
        template_options: -d centos -r 7 -a amd64
      become: yes
    - name: Crea contenedor lab01
      lxc_container:
        name: lab01
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac03 }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor lab02
      lxc_container:
        name: lab02
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac04 }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Crea contenedor lab03
      lxc_container:
        name: lab03
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac05 }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Pausa para esperar que levante contenedor
      pause:
        seconds: 10
    - name: Crea configuración base para contenedores en CentOS
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'nagiosxi' ]
        - [ '/usr/bin/yum update -y', '/usr/bin/yum install openssh-server sudo psmisc curl wget which -y', 'systemctl enable sshd', 'systemctl start sshd', 'useradd -s /bin/bash -G wheel -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore' , 'mkdir ~greencore/.ssh/', 'wget -O ~greencore/.ssh/authorized_keys https://raw.githubusercontent.com/fede2cr/ansible_greencore/master/files/authorized_keys', 'chown -R greencore:greencore ~greencore/.ssh' ]
      become: yes
    - name: Crea configuración base para contenedores en Ubuntu
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'web-base', 'lab01', 'lab02', 'lab03' ]
        - [ "sed -i 's/archive.ubuntu.com/ubuntu-mirror.greencore.int/g' /etc/apt/sources.list ", 'apt-get update', 'apt-get dist-upgrade -y', 'apt-get install python ssh sudo psmisc curl apache2 nano -y', 'systemctl enable ssh', 'systemctl start ssh', 'useradd -s /bin/bash -G sudo -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore' , 'mkdir ~greencore/.ssh/', 'wget -O ~greencore/.ssh/authorized_keys https://raw.githubusercontent.com/fede2cr/ansible_greencore/master/files/authorized_keys', 'chown -R greencore:greencore ~greencore/.ssh' ]
      become: yes
