---
- name: Crea contenedor para demo de bind
  hosts: 10.42.25.20
  tasks:
    - name: Apaga todos los contenedores
      command: "lxc-stop -n {{ item }}"
      with_items:
        - demobind
      become: yes
      ignore_errors: true
    - name: Destruye todos los contenedores
      command: "lxc-destroy -n {{ item }}"
      with_items:
        - demobind
      become: yes
      ignore_errors: true
    - name: Crea contenedor demobind
      lxc_container:
        name: demobind
        container_log: true
        container_config:
          - lxc.network.link = br0
          - lxc.start.auto = 1
          - lxc.start.delay = 10
          - lxc.start.order = 0
          - lxc.network.hwaddr = {{ mac04 }}
        template: download
        state: started
        template_options: -d ubuntu -r xenial -a amd64
      become: yes
    - name: Pausa para esperar que levante contenedor
      pause:
        seconds: 10
    - name: Crea configuración base para todos los contenedores
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'demobind' ]
        - [ 'apt-get update', 'apt-get dist-upgrade -y', 'apt-get install python ssh sudo psmisc bind9 git wget bind9utils bind9-host nano -y', 'systemctl enable ssh', 'systemctl start ssh', 'useradd -s /bin/bash -G sudo -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore', 'wget -O /etc/bind/named.conf.local https://raw.githubusercontent.com/fede2cr/ansible_greencore/master/cursos/curso_servidores_web_con_software_libre/lecciones/leccion-02-demo-dns-bind/named.conf.local', 'wget -O /etc/bind/db.greencore.int https://raw.githubusercontent.com/fede2cr/ansible_greencore/master/cursos/curso_servidores_web_con_software_libre/lecciones/leccion-02-demo-dns-bind/db.greencore.int', 'systemctl restart bind9' ]
      become: yes
