---
- name: Instala la máquina virtual de CentOS
  hosts: fisicos
  strategy: free
  tasks:
    - name: Instala paquetes requeridos por la receta
      apt:
        name: pbzip2
        state: present
      become: yes
    - name: Plantilla de jinja para XML de VM de CentOS
      template:
        src: files/CentOS.xml.j2
        dest: /tmp/CentOS.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de CentOS
      command: virsh define /tmp/CentOS.xml
      become: yes
    - name: Mueve imagen de CentOS a directorio de imagenes
      get_url:
        url: http://10.42.30.5/vms/CentOS.qcow2.bz2
        dest: /var/lib/libvirt/images/CentOS.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
      become: yes
    - name: Descomprime imagen de CentOS usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/CentOS.qcow2.bz2
      become: yes
    - name: Reinicia servicio libvirt-bin
      service:
        name: libvirt-bin
        state: restarted
      become: yes
