---
- name: Instala la máquina virtual de Ubuntu
  hosts: fisicos
  strategy: free
  tasks:
    - name: Instala paquetes requeridos por la receta
      apt:
        name: pbzip2
        state: present
      become: yes
    - name: Plantilla de jinja para XML de VM de ubuntu
      template:
        src: files/Alfresco.xml.j2
        dest: /tmp/Alfresco.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de ubuntu
      command: virsh define /tmp/Alfresco.xml
      become: yes
    - name: Mueve imagen de ubuntu-server a directorio de imagenes
      get_url:
        url: http://{{ filesrv }}/vms/Alfresco.qcow2.bz2
        dest: /var/lib/libvirt/images/Alfresco.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
      become: yes
    - name: Descomprime imagen de ubuntu usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/Alfresco.qcow2.bz2
      become: yes
    - name: Reinicia el servicio libvirt-bin
      service:
        name: libvirt-bin
        state: restarted
      become: yes
