---
- name: Agrega discos virtuales a Kali-vm para laboratorios forenses
  hosts: fisicos
  tasks:
    - name: Descarga vdb
      get_url:
        url: http://{{ filesrv }}/vms/forense/kali-1.qcow2.bz2
        dest: /var/lib/libvirt/images/kali-1.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
    - name: Descomprime imagen de kali usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/kali-1.qcow2.bz2
    - name: Agrega disco vdb a Kali-vm
      command: virsh attach-disk kali --source /var/lib/libvirt/images/kali-1.qcow2 --target vdb --persistent
      become: yes
    - name: Descarga vdc
      get_url:
        url: http://{{ filesrv }}/vms/forense/kali-2.qcow2.bz2
        dest: /var/lib/libvirt/images/kali-2.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
    - name: Descomprime imagen de kali usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/kali-2.qcow2.bz2
    - name: Agrega disco vdc a Kali-vm
      command: virsh attach-disk kali --source /var/lib/libvirt/images/kali-2.qcow2 --target vdc --persistent
      become: yes
    - name: Descarga vdd
      get_url:
        url: http://{{ filesrv }}/vms/forense/kali-3.qcow2.bz2
        dest: /var/lib/libvirt/images/kali-3.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
    - name: Descomprime imagen de kali usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/kali-3.qcow2.bz2
    - name: Agrega disco vdd a Kali-vm
      command: virsh attach-disk kali --source /var/lib/libvirt/images/kali-3.qcow2 --target vdd --persistent
      become: yes
