---
- name: Instala la máquina virtual de Kali
  hosts: fisicos
  tasks:
    - name: Plantilla de jinja para XML de VM de Kali
      template:
        src: ../files/rootkit.xml.j2
        dest: /tmp/rootkit.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de Rootkit
      command: virsh define /tmp/rootkit.xml
      become: yes
    - name: Mueve imagen de kali a directorio de imagenes
      get_url:
        url: http://{{ filesrv }}/vms/rootkit.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
        dest: /var/lib/libvirt/images/rootkit.qcow2.bz2
    - name: Descomprime imagen de rootkit usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/rootkit.qcow2.bz2
