---
- name: Crea contenedores necesarios para el curso
  hosts: fisicos
  tasks:
    - name: Apaga todos los contenedores
      command: "lxc-stop -n {{ item }}"
      with_items:
        - web-base
      become: yes
      ignore_errors: true
    - name: Destruye todos los contenedores
      command: "lxc-destroy -n {{ item }}"
      with_items:
        - web-base
      become: yes
      ignore_errors: true
