---
- name: Instala la máquina virtual de Kali
  hosts: fisicos
  strategy: free
  tasks:
    - name: Instala paquetes requeridos por los instructores
      apt:
        name: pbzip2
        state: present
      become: yes
    - name: Plantilla de jinja para XML de VM de Kali
      template:
        src: files/kali.xml.j2
        dest: /tmp/kali.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de Kali
      command: virsh define /tmp/kali.xml
      become: yes
    - name: Mueve imagen de kali a directorio de imagenes
      get_url:
        url: http://{{ filesrv }}/vms/kali.qcow2.bz2
        dest: /var/lib/libvirt/images/kali.qcow2.bz2
        mode: 0775
        owner: "{{ ansible_user }}"
      become: yes
    - name: Descomprime imagen de kali usando deteccion de threads
      command: pbzip2 -d /var/lib/libvirt/images/kali.qcow2.bz2
      become: yes
