---
- name: Instala la base para los equipos de los laboratorios de Greencore Solutions
  hosts: fisicos
  strategy: free
  tasks:
  - name: Remueve paquetes en conflicto con los laboratorios
    apt:
      name: ['modemmanager', 'deja-dup', 'aptdaemon', 'update-manager-core', 'unattended-upgrades', 'docker', 'docker-engine', 'docker.io']
      state: absent
    become: yes
  - name: Usa debconf para decirle a wireshark que permita escucha a usuarios no-root
    debconf:
      name: wireshark-common
      question: wireshark-common/install-setuid
      value: true
      vtype: boolean
    become: yes
  - name: Instala paquetes requeridos por los instructores
    apt:
      name: ['vim', 'virt-manager', 'virtualbox', 'fritzing', 'bridge-utils', 'qemu-kvm', 'qemu-system', 'libvirt-bin', 'ubuntu-vm-builder', 'pwgen', 'gnome-shell', 'gnome-tweak-tool', 'chromium-browser', 'screen', 'byobu', 'openssh-server', 'dia', 'shutter', 'vlc', 'mpv', 'wakeonlan', 'git', 'python3-pip', 'avahi-discover', 'udpcast', 'pv', 'docker-compose', 'nmap', 'wireshark', 'etherape', 'iftop', 'pbzip2', 'distcc', 'distcc-pump', 'distccmon-gnome', 'ccache', 'bison', 'flex', 'libncurses-dev', 'libelf-dev', 'libssl-dev', 'rtl-sdr', 'gqrx-sdr', 'nodejs', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'openjdk-8-jre', 'code']
      state: present
    become: yes
  - name: Instala paquete de Atom usando ATP
    apt:
      deb: https://github.com/atom/atom/releases/download/v1.29.0/atom-amd64.deb
      state: present
    become: yes
  - name: Instala módulos de python con pip3
    pip:
      name: ['asciinema', 'mu-editor', 'ansible', 'apio', 'pylint']
      state: latest
      executable: pip3
    become: yes
  - name: Instala módulos de python con pip
    pip:
      name: ['platformio']
      state: latest
    become: yes
  - name: Agrega a usuario ansible_user en grupos necesarios
    user:
      name: "{{ ansible_user }}"
      #      groups: wireshark,sudo,docker,dialout,libvirt
      groups: wireshark,sudo,docker,dialout
      append: yes
    become: yes
  - name: Agrega acl para poder modificar /usr/local como greencore
    acl:
      path: /usr/local
      entity: "{{ ansible_user }}"
      etype: user
      permissions: rwX
      state: present
      recursive: yes
    become: yes
  - name: Agrega acl para poder modificar /usr/lib/node_modules como greencore
    acl:
      path: /usr/lib/node_modules
      entity: "{{ ansible_user }}"
      etype: user
      permissions: rwX
      state: present
      recursive: yes
    become: yes
  - name: Instala paquetes de npm
    npm:
      name: "{{ item }}"
      global: yes
    with_items:
      - node-red
    become: yes
  #- name: Instala paquetes de npm
  #  npm:
  #    name: "{{ item }}"
  #    global: yes
  #  with_items:
  #    - terminalizer
  #  become: yes  
  - name: Instala PyCharm
    unarchive:
      src: https://download.jetbrains.com/python/pycharm-community-2019.1.2.tar.gz 
      mode: 0775
      owner: "{{ ansible_user }}"
      dest: "/usr/local/"
      remote_src: yes
    become: yes
  - name: Agrega Pycharm al PATH
    copy:
      dest: /etc/profile.d/pycharm-path.sh
      content: |
              #!/usr/bin/env bash
              export PATH=$PATH:/usr/local/pycharm-community-2018.2.3/bin/
      mode: 0755
      owner: root
      group: root
    become: yes
  - name: Instala extensiones de vscode
    command: /usr/share/code/bin/code --install-extension "{{ item }}"
    with_items:
      - vscoss.vscode-ansible
      - platformio.platformio-ide
      - zhwu95.riscv
      - ms-python.python
